version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: 'increase-if-necessary'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
