import type { Metadata } from 'next'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import '@/styles/globals.css'
import { cn } from '@/libs/cn'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${GeistSans.variable} ${GeistMono.variable}`,
          'bg-[#F6F6F3] dark:bg-[#0C0C0C] overflow-x-hidden'
        )}
      >
        {children}
      </body>
    </html>
  )
}
